
import JSZip from "jszip";
import { saveAs } from "file-saver";

interface AgentExportConfig {
    name: string;
    role: string;
    systemPrompt: string;
    tools: string[];
    autonomy: number;
    apiKey?: string; // Optional user key
}

export const exportAgentAsZip = async (agent: AgentExportConfig) => {
    const zip = new JSZip();
    const folderName = agent.name.toLowerCase().replace(/ /g, "-") + "-agent";
    const folder = zip.folder(folderName);

    if (!folder) return;

    // 1. Agent Configuration
    const config = {
        name: agent.name,
        role: agent.role,
        autonomy: agent.autonomy,
        tools: agent.tools,
        version: "1.0.0",
        generatedBy: "AgentForge AI",
    };

    folder.file("agent-config.json", JSON.stringify(config, null, 2));

    // 2. System Prompt
    folder.file("system-prompt.txt", agent.systemPrompt);

    // 3. Runtime Script (Node.js example using Vapi)
    const runtimeScript = `
import Vapi from "@vapi-ai/web"; // Or server SDK
// This is a browser-compatible example, for Node.js use the server SDK

const systemPrompt = \`${agent.systemPrompt.replace(/`/g, "\\`")}\`;

console.log("Starting agent: ${agent.name}");
console.log("Role: ${agent.role}");

// Configuration for Vapi
const agentConfig = {
  model: {
    provider: "openai",
    model: "gpt-3.5-turbo",
    messages: [
      {
        role: "system",
        content: systemPrompt,
      },
    ],
  },
  voice: {
    provider: "11labs",
    voiceId: "burt",
  },
  firstMessage: "Hello! I am ${agent.name}. How can I assist you?",
};

export default agentConfig;
`;
    folder.file("agent.js", runtimeScript.trim());

    // 4. README
    const readme = `
# ${agent.name}
**Role:** ${agent.role}
**Generated by:** AgentForge AI

## Overview
This is a portable AI agent configuration package. It contains the system prompt, configuration, and a basic runtime script.

## Files
- \`agent-config.json\`: Metadata and configuration.
- \`system-prompt.txt\`: The core instructions for the AI.
- \`agent.js\`: An example configuration object for Vapi or similar services.

## How to Use
1. Use the content of \`system-prompt.txt\` in your LLM calls (OpenAI, Anthropic, etc.).
2. Import \`agent.js\` into your Vapi or ElevenLabs project to deploy this voice agent.
`;
    folder.file("README.md", readme.trim());

    // Generate and Save
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${folderName}.zip`);
};
